version: '3.8'

services:
  mongo:
    image: mongo:7-jammy
    container_name: helpdesk-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
  
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: helpdesk-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=change-me-please-make-it-very-secure-and-keep-it-safe-in-prod
      - AUTO_CLOSE_ENABLED=true
      - CONFIDENCE_THRESHOLD=0.78
      - STUB_MODE=true
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules # Prevents node_modules from being overwritten

volumes:
  mongo-data: